variables:
  - &node_image 'node:lts-alpine'
  - path: &site_path
      - 'site/**'
      - '.crow/site.yaml'

when:
  - path: *site_path
    event: [push, pull_request, manual]

steps:
  - name: install-dependencies
    image: *node_image
    directory: site/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile

  - name: build-site
    image: *node_image
    directory: site/
    commands:
      - corepack enable
      - pnpm build

  - name: deploy-preview
    image: docker.io/woodpeckerci/plugin-surge-preview:latest
    settings:
      path: 'site/build/'
      surge_token:
        from_secret: SURGE_TOKEN
      forge_repo_token:
        from_secret: GITHUB_TOKEN_SURGE
    failure: ignore
    when:
      - path: *site_path
        event: [pull_request, pull_request_closed]
