variables:
  - &node_image 'node:lts-alpine'
  - path: &site_path
      - 'site/**'
      - '.crow/site.yaml'

when:
  - path: *site_path
    event: [push, pull_request, manual]

steps:
  - name: install-dependencies
    image: *node_image
    directory: site/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile

  - name: build-docusaurus
    image: *node_image
    directory: site/
    commands:
      - corepack enable
      - pnpm build
