variables:
  - &node_image 'node:lts-alpine'
  - &surge_image 'docker.io/woodpeckerci/plugin-surge-preview'
  - path: &site_path
      - 'site/**'
      - '.crow/site.yaml'

steps:
  - name: install-dependencies
    image: *node_image
    when:
      - path: *site_path
        event: [push, pull_request, manual]
    directory: site/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile

  - name: build-site
    image: *node_image
    when:
      - path: *site_path
        event: [push, pull_request, manual]
    directory: site/
    commands:
      - corepack enable
      - pnpm build

  - name: deploy-site
    image: *node_image
    when:
      - branch: main
        event: [push, manual]
    directory: site/
    commands:
      - apk add git
      - corepack enable
      - pnpm run deploy
    environment:
      GIT_USER:
        from_secret: git_user
      GIT_PASS:
        from_secret: git_pat_docs_site
      GIT_USER_NAME: crow-bot
      GIT_USER_EMAIL: deploy@crow.bot

  - name: deploy-site-preview
    image: *surge_image
    when:
      - path: *site_path
        event: [pull_request, pull_request_closed]
    settings:
      path: 'site/build/'
      surge_token:
        from_secret: SURGE_TOKEN
      forge_repo_token:
        from_secret: GITHUB_TOKEN_SURGE
    failure: ignore

  - name: teardown-site-preview
    image: *surge_image
    when:
      - event: [push]
        branch: main
    commands:
      - |
        set -eu

        msg="${CI_COMMIT_MESSAGE}"

        # Extract PR number from GitHub merge commit messages
        pr="$(printf '%s\n' "$msg" | grep -oE 'pull request #[0-9]+' | grep -oE '[0-9]+')"

        if [ -z "${pr:-}" ]; then
          echo "No PR number found; skipping teardown."
          exit 0
        fi

        domain="${CI_REPO_OWNER}-${CI_REPO_NAME}-pr-${pr}.surge.sh"

        echo "Tearing down Surge preview: $domain"
        surge teardown "$domain"
    environment:
      SURGE_TOKEN:
        from_secret: SURGE_TOKEN
    failure: ignore
