variables:
  - &node_image 'node:lts-alpine'
  - &surge_image 'docker.io/woodpeckerci/plugin-surge-preview'
  - path: &site_path
      - 'site/**'
      - '.crow/site.yaml'

steps:
  - name: install-dependencies
    image: *node_image
    when:
      - path: *site_path
        event: [push, pull_request, manual]
    directory: site/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile

  - name: build-site
    image: *node_image
    when:
      - path: *site_path
        event: [push, pull_request, manual]
    directory: site/
    commands:
      - corepack enable
      - pnpm build

  - name: deploy-site
    image: *node_image
    when:
      - branch: main
        event: [push, manual]
    directory: site/
    commands:
      - apk add git
      - corepack enable
      - pnpm run deploy
    environment:
      GIT_USER:
        from_secret: git_user
      GIT_PASS:
        from_secret: git_pat_docs_site
      GIT_USER_NAME: crow-bot
      GIT_USER_EMAIL: deploy@crow.bot

  - name: deploy-site-preview
    image: *surge_image
    when:
      - path: *site_path
        event: pull_request
    settings:
      path: 'site/build/'
      surge_token:
        from_secret: SURGE_TOKEN
      forge_repo_token:
        from_secret: GITHUB_TOKEN_SURGE
    failure: ignore

  - name: teardown-site-preview
    image: *surge_image
    when:
      - path: *site_path
        event: pull_request_closed
    settings:
      path: 'site/build/'
      surge_token:
        from_secret: SURGE_TOKEN
      forge_repo_token:
        from_secret: GITHUB_TOKEN_SURGE
    failure: ignore

  - name: debug-pr-close
    image: alpine:3.19
    when:
      - event: [pull_request_closed]
    commands:
      - echo "CI_PIPELINE_EVENT=$CI_PIPELINE_EVENT"
      - echo "CI_COMMIT_PULL_REQUEST=$CI_COMMIT_PULL_REQUEST"
      - env | sort
